### ISSUE TITLE
ScyllaDB Compatibility

### ISSUE THREAD

**Issue by PeterCorless** [bleemeo/squirreldb#2]
If SquirrelDB works with Apache Cassandra, could you also test for use with ScyllaDB? You can use our shard-aware GoCQL driver and GoCQLX extension:

https://github.com/scylladb/gocql

https://github.com/scylladb/gocqlx

It should be fully compatible. Would love to hear whether it works.

**Comment by PierreF** [comment]
Hello,

it's a good idea to test compatibility with ScyllaDB. We had done some test very early in the project, but since we use LWT transations which were only experimental at that time with stick with Apache Cassandra.

Since it now supported, it should indeed work out-of-the-box. I'll do some test and comment the result in this issue.

**Comment by PeterCorless** [comment]
Sounds good! one of my colleagues suggested you check this out when the time comes:

https://docs.scylladb.com/kb/lwt-differences/

**Comment by PierreF** [comment]
Closing the issue as I believe the question is answered. Feel free to re-open if you want more information.
